spring.application.name=backend
server.port=8080
server.address=0.0.0.0

# Cors
cors.allowed-origins=http://localhost:3000,http://127.0.0.1:3000

# Datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/superbatch_license
spring.datasource.username=postgres
spring.datasource.password=root

# Create/update tables automatically
spring.jpa.hibernate.ddl-auto=update
# See SQL in console
# spring.jpa.show-sql=true
# Pretty print SQL
# spring.jpa.properties.hibernate.format_sql=true


# Secret Key
jwt.secret=7e2f9d8c4b1a6f3fff9c1a7b5f2d8e6c
jwt.expiration=86400000

#License Private Key
license.private-key=MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCesCcIpFM+jfsbrMJcVmPzoEir/9uQ/c+kypcZ/Xqx6mznDORcYK+hjG92FtBNV3kS1/sJKKzcEh86ldOK3L/bgSL1OK0ROFWM3Ghq5z18BcZuHTvNZoUGGDZvPauDAWUvfDJg/HYtusvJHonmUFS6+lkSbstW+hDKwH2JhzmVVeh9V3ITbMSBc7aja+7FeqVsqPyk8mekuBFFNx+DwvdVgcb/69gjAD6DZZhTD/H1ou0qFJRVV4/eqiLPMbCIkJ+ndDFjqdPsIzNPayw8wPrDKB6Zp2fewpD52h8gTJ4e8RX1jdbbTVMa96m8wol4W4x1dILdJuEu4/keP550MyuXAgMBAAECggEAFJvIOKFCpa1BucU0vqeCNo8P27U65M3EQYtalpz/6grfAXNVVZaW6JI48tX2pRIMSWwJkEBwkT9nP9qvt5PV9MyvZ2Jovi5ElKpr2HUB2/v8r6tAliXPdnb+3BvfDNX0YqIsrBd4GkCX8PLJh5gne4WXZhiZHslovzQYJEa5WJE0acmGZnfQflX0skMfvGqRk2FOvZeLR09waAbbQYSZDH6wd2dkV5WXcxYWZolF3bg6+AiXvqj2UnyFyUQ9jlKmWzjHhxR2cp1pUkfA9qvqO+eByd+l784iaSa+qidFTJ7+LLbyS6y0dHCP1XXSceAyla5nG14txMSFYWiP8olguQKBgQDK76dW1A9Gfp2lHR9WmQPIzufbubtl59sl68GvfM4l+67LqHU2Pe5eMZ8d0AB+sWhU6bedm9thvKNiOioQI+OOCIewgVumMLg/lq0fmlVX0FOtf93IpnqG5LVDwyLUgfK0SUP/xgfVbIVZ7OvWjc1hdX5FV8BzyifenXzt/ck1HwKBgQDILpPkfEgxbDD/qqtHyy61qBRpS3n0X1Ve59iBqB/WZ/5qcUUKjCAyiu168wqBXk3A+/vRbNHZKKIY/j4HNqUysMf54KV4NU8C6Qz0/stHHYxwYJ+dD4X9I/FX9ewHTof1xYATZCBTVQOCv58yk7C/vWeEE4VNrX6+pDbdi/SCiQKBgDKJxlHAU+GJbLcO7pwBVUjwBhvZQEsbl570/HI4kZox+JDtbetJNxCsKOUixMzIX6Qt5DVS+Cp58PJoa8tDNMtNYoVZYbqcjXYAjzK8m55X2k7t9gyfMQpg8KdkdEsZ5ZhyWoXbCl5jPT5s2zq+a7Rmr0CTnvD3GkC9VbxrJG2fAoGAX+LvtGJTsljAn7aAlMMefKUmIcmlgQipO+ySKIj/txPZKeNXztWQFqW1W09PmOgzFl2dIZOecQalnpMp4wqp1r4XC/ovSIVAc4RuUGw7srTUsH+X9QOaisbMs/V4OYfEWFViI+eyFDiElfxzpSZZY362Nu2izLJuI6NFJJoFZQECgYEAuwkCpEehiqTrAukcxF5uc2NGGlkGUTvpP7HvMWZVwRp//oPE6Zm8fpdb9nTjsZy/YpBrcGRRnDKwMMaDA3e4avPJKIyhnvYsMovXk6jAVRT+llyXzKW3M421nvnA19kNaECp61YZPWLkLVo3259soEQDFvwSPnXKqTdfPKNAENc=

# Log
logging.level.root=INFO
logging.level.com.mvp.jobportal=INFO
logging.level.org.springframework=WARN
logging.level.org.springframework.boot.autoconfigure=ERROR
logging.level.org.springdoc=WARN
logging.level.com.zaxxer.hikari=OFF
logging.level.org.hibernate=WARN
logging.level.org.hibernate.orm.query=ERROR
logging.level.org.apache=WARN
logging.level.org.springframework.security=OFF
logging.level.org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver=OFF
logging.level.org.springframework.boot.devtools=OFF
spring.devtools.restart.enabled=true
spring.jpa.open-in-view=false
spring.main.banner-mode=off

# Human readable console logs
logging.pattern.console=%d{HH:mm:ss} %msg%n
# Human readable file logs
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{40} - %msg%n

# File logging
logging.file.name=logs/superbatch.log

# Rotate every 5MB
logging.logback.rollingpolicy.max-file-size=5MB
logging.logback.rollingpolicy.max-history=30
logging.logback.rollingpolicy.total-size-cap=500MB
logging.logback.rollingpolicy.file-name-pattern=logs/superbatch-%d{yyyy-MM-dd}.%i.log

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=manavpande2005@gmail.com
spring.mail.password=sosd puhn svts dkti
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


