spring.application.name=backend
server.port=8080
server.address=0.0.0.0

# Cors
cors.allowed-origins=http://localhost:3000,http://127.0.0.1:3000

# Datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/superbatch_license
spring.datasource.username=postgres
spring.datasource.password=root

# Create/update tables automatically
spring.jpa.hibernate.ddl-auto=update
# See SQL in console
# spring.jpa.show-sql=true
# Pretty print SQL
# spring.jpa.properties.hibernate.format_sql=true


# Secret Key
jwt.secret=7e2f9d8c4b1a6f3fff9c1a7b5f2d8e6c
jwt.expiration=86400000

# Log
logging.level.root=INFO
logging.level.com.mvp.jobportal=INFO
logging.level.org.springframework=WARN
logging.level.org.springframework.boot.autoconfigure=ERROR
logging.level.org.springdoc=WARN
logging.level.com.zaxxer.hikari=OFF
logging.level.org.hibernate=WARN
logging.level.org.hibernate.orm.query=ERROR
logging.level.org.apache=WARN
logging.level.org.springframework.security=OFF
logging.level.org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver=OFF
logging.level.org.springframework.boot.devtools=OFF
spring.devtools.restart.enabled=true
spring.jpa.open-in-view=false
spring.main.banner-mode=off

# Human readable console logs
logging.pattern.console=%d{HH:mm:ss} %msg%n
# Human readable file logs
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{40} - %msg%n

# File logging
logging.file.name=logs/superbatch.log

# Rotate every 5MB
logging.logback.rollingpolicy.max-file-size=5MB
logging.logback.rollingpolicy.max-history=30
logging.logback.rollingpolicy.total-size-cap=500MB
logging.logback.rollingpolicy.file-name-pattern=logs/superbatch-%d{yyyy-MM-dd}.%i.log

